name: MLOps Automation Pipeline

on:
  push:
    branches: ["otomatization"]
  pull_request:
    branches: ["otomatization"]

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
    # ======================
    # 1. SETUP ENV
    # ======================
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    # ======================
    # 2. GET DATA (WAJIB DULUAN)
    # ======================
    - name: Pull data from DVC
      run: |
        dvc pull

    # ======================
    # 3. TESTING
    # ======================
    - name: Run unit tests
      run: |
        pytest -v

    # ======================
    # 4. TRAINING
    # ======================
    - name: Train model
      run: |
        python src/train.py

    # ======================
    # 5. EVALUATION
    # ======================
    - name: Evaluate model
      run: |
        python src/evaluate.py

    # ======================
    # 6. REGISTER MODEL
    # ======================
    - name: Register model to MLflow
      if: success()
      run: |
        python src/register_model.py
