name: MLOps Automation Pipeline

on:
  push:
    branches: ["otomatization"]
  pull_request:
    branches: ["otomatization"]

env:
  MINIO_ENDPOINT_URL: ${{ secrets.MINIO_ENDPOINT_URL }}
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  TRAIN_DATA: 'data/processed/cleaned_data.csv'

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
    # ======================
    # 1. SETUP ENV
    # ======================
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # ======================
    # 2. GET DATA (WAJIB DULUAN)
    # ======================
    - name: Configure DVC remote
      run: |
        dvc remote modify minio endpointurl $MINIO_ENDPOINT_URL
        dvc remote modify --local minio access_key_id $MINIO_ACCESS_KEY
        dvc remote modify --local minio secret_access_key $MINIO_SECRET_KEY
      env:
        MINIO_ENDPOINT_URL: ${{ env.MINIO_ENDPOINT_URL }}
        MINIO_ACCESS_KEY: ${{ env.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ env.MINIO_SECRET_KEY }}

    - name: Pull data from DVC
      run: |
        dvc pull ${{ env.TRAIN_DATA }} --no-run-cache

    # ======================
    # 3. TESTING
    # ======================
    - name: Run unit tests
      run: |
        pytest -v

    # ======================
    # 4. TRAINING
    # ======================
    - name: Train model
      run: |
        python src/train.py

    # ======================
    # 5. EVALUATION
    # ======================
    - name: Evaluate model
      run: |
        python src/evaluate.py

    # ======================
    # 6. REGISTER MODEL
    # ======================
    - name: Register model to MLflow
      if: success()
      run: |
        python src/register_model.py
