name: MLOps Automation Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # ======================
    # 1. TESTING
    # ======================
    - name: Run unit tests
      run: |
        pytest

    # ======================
    # 2. DVC PULL (DATA)
    # ======================
    - name: Pull data from DVC
      run: |
        pip install dvc
        dvc pull

    # ======================
    # 3. TRAINING
    # ======================
    - name: Train model
      run: |
        python src/train.py

    # ======================
    # 4. EVALUATION
    # ======================
    - name: Evaluate model
      run: |
        python src/evaluate.py

    # ======================
    # 5. REGISTER TO MLFLOW
    # ======================
    - name: Register model to MLflow
      if: success()
      run: |
        python src/register_model.py